[package]
name = "renderer"
version = "0.1.0"
authors = ["Owen Campbell <ocampbell95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
glam = "0.17.3"